apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: yourrepo/url-shortener:latest
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: "https://short.example.com"
            - name: DB_TYPE
              value: "cassandra"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: CASSANDRA_HOSTS
              value: "cassandra"
            - name: CASSANDRA_KEYSPACE
              value: "urlshort"
            - name: MACHINE_ID
              value: "1"
